name: Deploy FastAPI

on:
  push:
    branches:
      - main
      - master

# allow only one process
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy with Uvicorn
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &

      # - name: Run FastAPI Server (Test)  # ✅ Start FastAPI to ensure it runs properly
      #   run: |
      #     nohup uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Check Running Services  # ✅ Ensure the app is running
        run: |
          sleep 5  # Wait for the server to start
          curl --fail http://localhost:8000/docs || exit 1

      - name: Deploy to Production (Optional)  # ✅ Add deployment steps if needed
        run: echo "Deployment completed successfully!"

      - name: Show Deployed URL
        run: echo "Your FastAPI app is available at https://marut-tandel.github.io/fast_api/.onrender.com"

